spring:
  application:
    name: spring-aot-demo
  datasource:
    url: jdbc:h2:mem:aotdemo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update   # auto-create tables
    show-sql: true       # log SQL to console
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,startup